name: everylounge
description: Application for ordering business lounges.

publish_to: 'none'
version: 2.5.1+25100

environment:
  sdk: '>=3.2.3 <4.0.0'

# To automatically upgrade your package dependencies to the latest versions
# `flutter pub upgrade --major-versions`.
# To see which dependencies have newer versions available
# `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  #language/flutter extensions/core
  equatable: 2.0.5 # for == realisation
  flutter_stream_listener: 2.0.0 #for messages from cubits and navigation
  get_it: 7.6.0 #di injection
  duration: 3.0.12 # for simple usage Duration
  provider: 6.0.5 # for provide custom theme model in all app
  easy_debounce: 2.0.3
  rxdart: 0.27.7
  protobuf: 3.1.0
  async: 2.11.0
  device_info_plus: 9.0.1
  package_info_plus: 4.0.1
  universal_html: 2.2.3 #for use html and js in non web applications
  flutter_html: ^3.0.0-beta.2

  #metrics
  appmetrica_plugin: 1.4.0

  #network
  dio: 4.0.4 #http client 4.0.4 work well with web, 4.0.6 work bad
  firebase_core: ^2.25.4 #firebase services
  firebase_remote_config: 4.3.14 #for fetching credentials from remote
  firebase_analytics: 10.8.6 # for working  [firebase_remote_config]
  grpc: 3.2.4


  #storage
  hive: 2.2.3
  hive_flutter: 1.1.0


  #logging
  logger: 1.3.0
  sentry_flutter: 7.12.0
  debug_overlay: 0.2.8

  #presentation
  flutter_bloc: 8.1.3
  go_router: 11.1.2
  flutter_svg: 2.0.9

  auto_size_text: 3.0.0
  modal_bottom_sheet: 3.0.0-pre
  intl: 0.18.1
  pin_code_fields: 7.4.0
  timer_count_down: 2.2.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  dotted_decoration: 2.0.0
  image_picker: 0.8.7+5
  extended_masked_text: 2.3.1
  webview_flutter: 4.7.0
  scrollable_positioned_list: 0.3.8
  flutter_rating_bar: 4.0.1
  launch_app_store: 1.0.2
  dropdown_button2: 2.1.3
  shimmer: 3.0.0
  animated_snack_bar: 0.4.0
  top_snackbar_flutter: 3.1.0
  syncfusion_flutter_gauges: 21.2.4
  slide_switcher: 1.1.2 # for custom 3 elements swither
  flutter_switch: 0.3.2 # for custom true/false switcher
  flutter_keyboard_visibility: 6.0.0
  expandable: 5.0.1
  rate_my_app: 2.0.0
  custom_refresh_indicator: 2.2.1
  cached_network_image: 3.3.1
  infinity_page_view_astro: 1.0.0
  flutter_cached_pdfview: 0.4.2

  #links
  app_links: 3.5.0 # для управления входящими ссылками в наше приложение
  url_launcher: 6.1.11 # для запуска Uri из нашего приложения
  share_plus: 7.0.2 #для того, чтобы делиться скриншотами
  screenshot: # для создания изображения из заказа для совместного использования
    git:
      url: https://github.com/SachinGanesh/screenshot.git # для определения высоты скриншота

  #social
  google_sign_in: 5.4.4
  sign_in_with_apple: 4.3.0
  firebase_auth: 4.17.5
  tinkoff_id_web:
    git: https://github.com/kodefabrique/tinkoff_id_web.git
  tinkoff_id_flutter: 1.0.1
  pkce: ^1.1.0+1 #for tinkoff id web

  #permission
  permission_handler: 10.2.0

  #acquiring
  tinkoff_acquiring_flutter: 3.0.10
  tinkoff_acquiring: 3.0.10
  tinkoff_acquiring_native_flutter:
    git: https://github.com/kodefabrique/tinkoff_acquiring_native_flutter
#   path: tinkoff_acquiring_native_flutter

  native_launcher:
    git: https://github.com/kodefabrique/flutter_native_launcher
    # path: ../native_launcher

  #utils
  translit: 2.0.1 #for translit passengers names when order is created
  geolocator: 11.0.0
  upgrader: 8.2.0 #check app version and upgarde
  flutter_flavor: 3.1.1
  qr_flutter: 4.1.0
  image_cropper: 4.0.1 #upgarde after remove tinkoff_acquiring 3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: 0.12.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
  image_path: "assets/icons/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/splash/
    - assets/images/banks/
    - assets/images/banks/big_circles/
    - assets/images/banks/small_circles/
    - assets/images/banks/payment_systems/
    - assets/images/common/
    - assets/images/profile/
    - assets/images/home/
    - assets/images/icons/
    - assets/images/bottom_menu/
    - assets/images/info/
    - assets/images/socials/
    - assets/images/history/
    - assets/images/lounge/
    - assets/images/lounge/org_logo/
    - assets/images/fly/
    - assets/images/upgrade_flight/
    - assets/images/loader/
    - assets/icons/
    - assets/ca/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Neue Haas Unica
      fonts:
        - asset: assets/fonts/NeueHaasUnica-Regular.ttf
          weight: 300
        - asset: assets/fonts/NeueHaasUnica-Bold.ttf
          weight: 700
