// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV1wGoqIX9CeOZllBzVVP6jCfkWwpVlVc',
    appId: '1:1055014541217:web:52ffdd58d6067787de9de0',
    messagingSenderId: '1055014541217',
    projectId: 'every-lounge',
    authDomain: 'every-lounge.firebaseapp.com',
    storageBucket: 'every-lounge.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqOYTsn8myV1QvnMeEyUsY9TONuTHzt-E',
    appId: '1:1055014541217:android:46935cddbac21eb7de9de0',
    messagingSenderId: '1055014541217',
    projectId: 'every-lounge',
    storageBucket: 'every-lounge.appspot.com',
  );

  static FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyC__c46oqT2z2fHMUvF2qIWHfMKPVruOxA',
    appId: '1:1055014541217:ios:5c877efebab73088de9de0',
    messagingSenderId: '1055014541217',
    projectId: 'every-lounge',
    storageBucket: 'every-lounge.appspot.com',
    androidClientId: '1055014541217-5vvck8kbg52stom25h0vie2j7g0mh3hq.apps.googleusercontent.com',
    iosClientId: '1055014541217-8t8001vv364jrq0qnsohsc8bc3a8eeaf.apps.googleusercontent.com',
    iosBundleId: 'com.everylounge',
  );
}
